import type { PrismaClient } from "../../../../generated/prisma/client";
import { daysAgo, hoursAgo } from "../helpers";
import type { SeedContext } from "../types";

export async function seedNotifications(
  db: PrismaClient,
  ctx: SeedContext,
): Promise<SeedContext> {
  await db.notification.createMany({
    data: [
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        merchantId: ctx.apexId,
        type: "LOW_STOCK",
        severity: "WARNING",
        title: "Low stock alert — APEX-TS-BLK-S",
        body: "Performance T-Shirt Black S has 12 units remaining across all locations — below the threshold of 20.",
        channel: "IN_APP",
        sentAt: hoursAgo(3),
        readAt: null,
        createdAt: hoursAgo(3),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        merchantId: ctx.novatechId,
        type: "STOCKOUT_RISK",
        severity: "CRITICAL",
        title: "Stockout risk — NOVA-TWS-001",
        body: "True Wireless Earbuds Pro is projected to stock out in 4 days at current sales velocity. Reorder immediately.",
        channel: "IN_APP",
        sentAt: hoursAgo(1),
        readAt: null,
        createdAt: hoursAgo(1),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        type: "SLA_BREACH",
        severity: "WARNING",
        title: "SLA at risk — 3 orders approaching 48h limit",
        body: "3 orders for Apex Sportswear are within 4 hours of breaching the 48-hour fulfillment SLA.",
        channel: "IN_APP",
        sentAt: hoursAgo(2),
        readAt: null,
        createdAt: hoursAgo(2),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        type: "INVOICE_OVERDUE",
        severity: "CRITICAL",
        title: "Invoice overdue — NovaTech Electronics",
        body: "Invoice INV-2024-005 for $3,847.00 is now 12 days overdue. Payment was due on May 30, 2024.",
        channel: "IN_APP",
        sentAt: daysAgo(0),
        readAt: null,
        createdAt: daysAgo(0),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        type: "ORDER_EXCEPTION",
        severity: "WARNING",
        title: "Carrier exception — order ORD-SHO-0003",
        body: "FedEx reported a delivery exception for tracking 1Z999AA10123456784. Address undeliverable.",
        channel: "IN_APP",
        sentAt: daysAgo(1),
        readAt: daysAgo(1),
        createdAt: daysAgo(1),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        type: "SHIPMENT_DELIVERED",
        severity: "INFO",
        title: "Shipment delivered — ORD-SHO-0008",
        body: "Package delivered to Emma Johnson at 1234 Main St, Los Angeles CA 90001 at 2:47 PM.",
        channel: "IN_APP",
        sentAt: daysAgo(2),
        readAt: daysAgo(2),
        createdAt: daysAgo(2),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        merchantId: ctx.apexId,
        type: "INVOICE_GENERATED",
        severity: "INFO",
        title: "Invoice generated — Apex Sportswear",
        body: "Invoice INV-2024-004 for the period May 1–31, 2024 has been generated. Total: $2,156.50.",
        channel: "IN_APP",
        sentAt: daysAgo(5),
        readAt: daysAgo(4),
        createdAt: daysAgo(5),
      },
      {
        accountId: ctx.accountId,
        userId: ctx.ownerAccountUserId,
        type: "CARRIER_EXCEPTION",
        severity: "WARNING",
        title: "UPS rate anomaly detected",
        body: "UPS Ground rates for zone 7 shipments have increased by 8.3% compared to last month. LogIQ recommends reviewing your carrier mix.",
        channel: "IN_APP",
        sentAt: daysAgo(3),
        readAt: daysAgo(3),
        createdAt: daysAgo(3),
      },
    ],
  });

  return ctx;
}
